-- ==========================================
-- SOLUÇÃO DEFINITIVA PARA COMUNIDADE E CHAT (V2)
-- ==========================================

-- 1. TABELA DE POSTS (Feed da Comunidade)
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  content text not null,
  image_url text,
  likes int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  user_name text,
  user_badge text,
  user_level int,
  user_avatar_id text
);

-- RLS para Posts
alter table public.posts enable row level security;
drop policy if exists "Posts are viewable by everyone." on public.posts;
drop policy if exists "Authenticated users can insert posts." on public.posts;
drop policy if exists "Authenticated users can update posts." on public.posts;
drop policy if exists "Users can update own posts." on public.posts;
drop policy if exists "Users can delete own posts." on public.posts;

create policy "Posts are viewable by everyone." on public.posts for select using (true);
create policy "Authenticated users can insert posts." on public.posts for insert with check (auth.role() = 'authenticated');
create policy "Users can update own posts." on public.posts for update using (auth.uid() = user_id);
create policy "Users can delete own posts." on public.posts for delete using (auth.uid() = user_id);

-- 2. TABELA DE CHAT (Bate-papo ao vivo)
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  user_name text not null default 'Atleta Anônimo',
  user_level int default 1,
  user_avatar_id text,
  content text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- RLS para Chat
alter table public.chat_messages enable row level security;
drop policy if exists "Chat messages are viewable by everyone." on public.chat_messages;
drop policy if exists "Authenticated users can insert chat messages." on public.chat_messages;
drop policy if exists "Users can delete own chat messages." on public.chat_messages;

create policy "Chat messages are viewable by everyone." on public.chat_messages for select using (true);
create policy "Authenticated users can insert chat messages." on public.chat_messages for insert with check (auth.role() = 'authenticated');
create policy "Users can delete own chat messages." on public.chat_messages for delete using (auth.uid() = user_id);

-- 3. TABELA DE COMENTÁRIOS
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  user_name text not null default 'Atleta Anônimo',
  user_level int default 1,
  user_avatar_id text,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- RLS para Comentários
alter table public.comments enable row level security;
drop policy if exists "Comments are viewable by everyone." on public.comments;
drop policy if exists "Authenticated users can insert comments." on public.comments;
drop policy if exists "Users can delete own comments." on public.comments;

create policy "Comments are viewable by everyone." on public.comments for select using (true);
create policy "Authenticated users can insert comments." on public.comments for insert with check (auth.role() = 'authenticated');
create policy "Users can delete own comments." on public.comments for delete using (auth.uid() = user_id);

-- 4. FUNÇÃO PARA LIKES (RPC)
create or replace function public.increment_likes(post_id bigint)
returns void as $$
begin
  update public.posts
  set likes = likes + 1
  where id = post_id;
end;
$$ language plpgsql security definer;

-- 5. HABILITAR REALTIME (CRITICAL)
do $$
begin
  -- Tenta adicionar as tabelas à publicação de realtime
  begin
    alter publication supabase_realtime add table chat_messages;
  exception when others then null; end;
  begin
    alter publication supabase_realtime add table posts;
  exception when others then null; end;
  begin
    alter publication supabase_realtime add table comments;
  exception when others then null; end;
end $$;

-- 6. GRANT PERMISSIONS
grant all on table public.posts to authenticated;
grant all on table public.chat_messages to authenticated;
grant all on table public.comments to authenticated;
grant all on sequence public.posts_id_seq to authenticated;
grant all on sequence public.chat_messages_id_seq to authenticated;
grant all on sequence public.comments_id_seq to authenticated;
grant all on table public.posts to anon;
grant all on table public.chat_messages to anon;
grant all on table public.comments to anon;
