-- ==========================================
-- SOLUÇÃO DEFINITIVA (V3) - REPARO DE COLUNAS
-- Este script força a existência de todas as colunas necessárias
-- ==========================================

-- 1. REPARAR TABELA DE POSTS
create table if not exists public.posts (id bigint generated by default as identity primary key);

alter table public.posts add column if not exists user_id uuid references auth.users(id);
alter table public.posts add column if not exists content text;
alter table public.posts add column if not exists image_url text;
alter table public.posts add column if not exists likes int default 0;
alter table public.posts add column if not exists created_at timestamp with time zone default now();
alter table public.posts add column if not exists user_name text;
alter table public.posts add column if not exists user_badge text;
alter table public.posts add column if not exists user_level int;
alter table public.posts add column if not exists user_avatar_id text;

-- 2. REPARAR TABELA DE CHAT
create table if not exists public.chat_messages (id bigint generated by default as identity primary key);

alter table public.chat_messages add column if not exists user_id uuid references auth.users(id);
alter table public.chat_messages add column if not exists user_name text default 'Atleta Anônimo';
alter table public.chat_messages add column if not exists user_level int default 1;
alter table public.chat_messages add column if not exists user_avatar_id text;
alter table public.chat_messages add column if not exists content text;
alter table public.chat_messages add column if not exists image_url text;
alter table public.chat_messages add column if not exists created_at timestamp with time zone default now();

-- 3. REPARAR TABELA DE COMENTÁRIOS
create table if not exists public.comments (id bigint generated by default as identity primary key);

alter table public.comments add column if not exists post_id bigint references public.posts(id) on delete cascade;
alter table public.comments add column if not exists user_id uuid references auth.users(id);
alter table public.comments add column if not exists user_name text default 'Atleta Anônimo';
alter table public.comments add column if not exists user_level int default 1;
alter table public.comments add column if not exists user_avatar_id text;
alter table public.comments add column if not exists content text;
alter table public.comments add column if not exists created_at timestamp with time zone default now();

-- 4. FUNÇÃO PARA LIKES (RE-CRIAR)
create or replace function public.increment_likes(post_id bigint)
returns void as $$
begin
  update public.posts
  set likes = coalesce(likes, 0) + 1
  where id = post_id;
end;
$$ language plpgsql security definer;

-- 5. RESETAR POLÍTICAS (Limpando tudo antes)
alter table public.posts enable row level security;
alter table public.chat_messages enable row level security;
alter table public.comments enable row level security;

do $$
begin
    -- Posts
    drop policy if exists "Posts are viewable by everyone." on public.posts;
    drop policy if exists "Authenticated users can insert posts." on public.posts;
    drop policy if exists "Users can update own posts." on public.posts;
    drop policy if exists "Users can delete own posts." on public.posts;
    
    -- Chat
    drop policy if exists "Chat messages are viewable by everyone." on public.chat_messages;
    drop policy if exists "Authenticated users can insert chat messages." on public.chat_messages;
    drop policy if exists "Users can delete own chat messages." on public.chat_messages;
    
    -- Comments
    drop policy if exists "Comments are viewable by everyone." on public.comments;
    drop policy if exists "Authenticated users can insert comments." on public.comments;
    drop policy if exists "Users can delete own comments." on public.comments;
end $$;

-- Aplicar novas políticas
create policy "Posts are viewable by everyone." on public.posts for select using (true);
create policy "Authenticated users can insert posts." on public.posts for insert with check (true); -- Temporariamente permissivo para teste
create policy "Users can update own posts." on public.posts for update using (true);
create policy "Users can delete own posts." on public.posts for delete using (true);

create policy "Chat messages are viewable by everyone." on public.chat_messages for select using (true);
create policy "Authenticated users can insert chat messages." on public.chat_messages for insert with check (true);
create policy "Users can delete own chat messages." on public.chat_messages for delete using (true);

create policy "Comments are viewable by everyone." on public.comments for select using (true);
create policy "Authenticated users can insert comments." on public.comments for insert with check (true);
create policy "Users can delete own comments." on public.comments for delete using (true);

-- 6. GARANTIR PERMISSÕES TOTAIS
grant all on all tables in schema public to anon, authenticated, postgres, service_role;
grant all on all sequences in schema public to anon, authenticated, postgres, service_role;
grant all on all functions in schema public to anon, authenticated, postgres, service_role;

-- 7. RE-SINCRONIZAR REALTIME
drop publication if exists supabase_realtime;
create publication supabase_realtime for table chat_messages, posts, comments;
