-- Migration: Notifications System
-- Run this in Supabase SQL Editor

-- Table to store push subscriptions
create table if not exists public.notification_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  subscription jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, subscription) -- Avoid duplicate subscriptions per device
);

-- RLS for subscriptions
alter table public.notification_subscriptions enable row level security;
create policy "Users can manage own subscriptions." on public.notification_subscriptions for all using (auth.uid() = user_id);

-- Table for scheduled notifications (incentives)
create table if not exists public.scheduled_notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  schedule_time time not null, -- Time of day to send (e.g., '08:00')
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- RLS for scheduled_notifications
alter table public.scheduled_notifications enable row level security;
create policy "Everyone can read scheduled notifications." on public.scheduled_notifications for select using (true);
create policy "Only admins can manage scheduled notifications." on public.scheduled_notifications for all using (
  auth.uid() in (select id from public.profiles where email = 'admin@example.com') -- Replace with actual admin check or role
);
