-- Migration: Notifications System (Safe to re-run)

-- 1. Create table for subscriptions if it doesn't exist
create table if not exists public.notification_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  subscription jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, subscription)
);

-- 2. Enable RLS
alter table public.notification_subscriptions enable row level security;

-- 3. Safely create/update policies
drop policy if exists "Users can manage own subscriptions." on public.notification_subscriptions;
drop policy if exists "Users can insert own subscription." on public.notification_subscriptions;
drop policy if exists "Users can update own subscription." on public.notification_subscriptions;

create policy "Users can manage own subscriptions." 
on public.notification_subscriptions 
for all 
using (auth.uid() = user_id);

-- 4. Create table for scheduled notifications
create table if not exists public.scheduled_notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  schedule_time time not null,
  "repeat" text default 'daily',
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. Enable RLS for scheduled_notifications
alter table public.scheduled_notifications enable row level security;

drop policy if exists "Everyone can read scheduled notifications." on public.scheduled_notifications;
drop policy if exists "Anyone can manage scheduled notifications." on public.scheduled_notifications;

create policy "Everyone can read scheduled notifications." 
on public.scheduled_notifications 
for select 
using (true);

create policy "Anyone can manage scheduled notifications." 
on public.scheduled_notifications 
for all 
using (true);

-- 6. Create table for admin broadcast messages (instant push)
create table if not exists public.admin_broadcasts (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  sent_at timestamp with time zone default timezone('utc'::text, now())
);

-- 7. Enable RLS for admin_broadcasts
alter table public.admin_broadcasts enable row level security;

drop policy if exists "Everyone can read broadcasts." on public.admin_broadcasts;
drop policy if exists "Anyone can insert broadcasts." on public.admin_broadcasts;

create policy "Everyone can read broadcasts." 
on public.admin_broadcasts 
for select 
using (true);

create policy "Anyone can insert broadcasts." 
on public.admin_broadcasts 
for all 
using (true);