-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Profiles table (extends auth.users)
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  name text default 'Atleta Exemplo',
  level int default 12,
  xp int default 2450,
  streak int default 12,
  completed_workouts int default 48,
  photo text,
  avatar jsonb default '{"helmet": {"id": 1, "emoji": "⛑️", "name": "Elmo Básico", "color": "#8B4513"}, "armor": {"id": 1, "emoji": "🛡️", "name": "Escudo de Ferro", "color": "#708090"}, "weapon": {"id": 1, "emoji": "🗡️", "name": "Espada Curta", "color": "#C0C0C0"}, "background": {"id": 1, "name": "Arena Clássica", "gradient": "linear-gradient(135deg, #2c1810, #4a3020)"}}'::jsonb,
  stats jsonb default '{"power": 55, "strength": 50, "endurance": 60, "discipline": 45}'::jsonb,
  badges jsonb default '[{"id": 1, "name": "Primeiros Passos", "icon": "🥉", "description": "Completou o primeiro desafio"}, {"id": 2, "name": "Fogo Constante", "icon": "🔥", "description": "7 dias de sequência"}, {"id": 3, "name": "Guerreiro", "icon": "⚔️", "description": "Completou um desafio Elite"}]'::jsonb,
  challenge_profile jsonb,
  defeated_bosses jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Trigger to create profile entirely
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'name', 'Novo Atleta'));
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger if exists to avoid duplication errors on multiple runs
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Challenges table
create table if not exists public.challenges (
  id bigint generated by default as identity primary key,
  title text not null,
  level int default 1,
  xp int default 100,
  locked boolean default false,
  price int default 0,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Insert default challenges (ignore if exist)
-- Note: 'on conflict' requires a constraint, so we can't easily do it for generic inserts without a unique key aside from ID.
-- We'll assume this is a run-once script or users will manage duplicates.
insert into public.challenges (title, level, xp, locked, price, description) 
select 'Iniciante: Flexões', 1, 100, false, 0, 'Faça 10 flexões seguidas.'
where not exists (select 1 from public.challenges where title = 'Iniciante: Flexões');

insert into public.challenges (title, level, xp, locked, price, description) 
select 'Iniciante: Agachamentos', 1, 150, false, 0, 'Faça 20 agachamentos.'
where not exists (select 1 from public.challenges where title = 'Iniciante: Agachamentos');

insert into public.challenges (title, level, xp, locked, price, description) 
select 'Intermediário: Burpees', 5, 500, true, 100, 'Série de 3x10 Burpees.'
where not exists (select 1 from public.challenges where title = 'Intermediário: Burpees');

insert into public.challenges (title, level, xp, locked, price, description) 
select 'Elite: Iron Man', 10, 2000, true, 500, 'Corrida 5km + 100 Flexões.'
where not exists (select 1 from public.challenges where title = 'Elite: Iron Man');


-- Posts table
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  content text not null,
  likes int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  user_name text,
  user_badge text,
  user_level int
);

-- RLS
alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Users can update own profile." on public.profiles for update using (auth.uid() = id);

alter table public.challenges enable row level security;
create policy "Challenges are viewable by everyone." on public.challenges for select using (true);
create policy "Everyone can insert challenges." on public.challenges for insert with check (true);
create policy "Everyone can update challenges." on public.challenges for update using (true);
create policy "Everyone can delete challenges." on public.challenges for delete using (true);

alter table public.posts enable row level security;
create policy "Posts are viewable by everyone." on public.posts for select using (true);
create policy "Authenticated users can insert posts." on public.posts for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update posts." on public.posts for update using (auth.role() = 'authenticated'); 
create policy "Users can delete own posts." on public.posts for delete using (true);
